### ISSUE TITLE
Remove second redis upgrade test

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-icd-redis#412]
We don't need 2 upgrade tests - I suggest to remove `TestRunAdvancedExampleUpgrade` and just leave the DA upgrade test

**Comment by rajatagarwal-ibm** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-icd-redis/pull/414

**Comment by shemau** [comment]
Resolved by #413. There is no new version since there are no external changes to the module.
