### ISSUE TITLE
ICD Redis Shared with Small Preset 

### ISSUE THREAD

**Issue by vaseemw** [terraform-ibm-modules/terraform-ibm-icd-redis#425]
### Affected modules

*terraform-ibm-icd-redis 

### Terraform CLI and Terraform provider versions

* Terraform version: 1.9.1
* Provider version: latest 

### Expected behavior

It should be able to create a resource with Small Preset having vCPU 0.5

### Actual behavior

Warning: Note: IBM Cloud Databases released new Hosting Models on May 1. All existing multi-tenant instances will have their resources adjusted to Shared Compute allocations during August 2024. To monitor your current resource needs, and learn about how the transition to Shared Compute will impact your instance, see our documentation https://cloud.ibm.com/docs/cloud-databases?topic=cloud-databases-hosting-models
│
│   with module.icd-redis["instance1"].ibm_database.redis_database,
│   on .terraform\modules\icd-redis\main.tf line 57, in resource "ibm_database" "redis_database":
│   57: resource "ibm_database" "redis_database" {
│
╵
╷
│ Error: Attribute must be a whole number, got 0.5
│
│   with module.icd-redis["instance1"].ibm_database.redis_database,
│   on .terraform\modules\icd-redis\main.tf line 57, in resource "ibm_database" "redis_database":
│   57: resource "ibm_database" "redis_database" {
│
╵

### Steps to reproduce (including links and screen captures)

Do try to create icd with small preset size vCPU 0.5 

1. Run `terraform apply`

### Anything else

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
Potentially a provider issue: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5680

**Comment by iamar7** [comment]
As per the [response](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5680#issuecomment-2374067817) from the provider team, setting CPU to 0 provision a database with a true CPU of 0.5
