### ISSUE TITLE
[Redis DA]Add support to use a different KMS key for backup encryption

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-icd-redis#451]
See https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/issues/509

**Comment by maheshwarishikha** [comment]
@ocofaigh @Aayush-Abhyarthi 
Any specific reason that we are adding this feature only in DA not in module?

Module users may also require this functionality.

**Comment by ocofaigh** [comment]
@maheshwarishikha Its already supported in the main module to use a different KMS key for backup (see [here](https://github.com/terraform-ibm-modules/terraform-ibm-icd-redis/blob/5a2341c256642c3a3c5e1314ebd746c7ef77b779/variables.tf#L209)).

We don't create the keys in the module, and never have done. Thats only something we do in DAs.

**Comment by ocofaigh** [comment]
@maheshwarishikha Looking at the PR though, I think you are correct. The module is missing the auth policy creation is the user is passing a KMS key from a different KMS. However we still need one in the DA for cross account support

**Comment by Aayush-Abhyarthi** [comment]
@ocofaigh Do I need to do any changes in the PR then?

**Comment by ocofaigh** [comment]
@Aayush-Abhyarthi As per my above [comment](https://github.com/terraform-ibm-modules/terraform-ibm-icd-redis/issues/451#issuecomment-2513964564), if a user was consuming the module directly, and if they were using a KMS key for backups from a different KMS instance than was used for disk encryption, then there would be no auth policy created to cover the backup instance. That is a gap it seems in all our ICD modules currently. You seem to be solving it in your PR, but only for the DA.The point @maheshwarishikha was making is that is also needs to be solved in the module. You still need it in the DA too, but only to cover the cross account KMS use case.

**Comment by ocofaigh** [comment]
@Aayush-Abhyarthi Considering the gap in the module has always been there, and its nothing new that your introducing in your PR, I am going to merge your PR.
@jor2 is going to do a tidy up exercise against our 3 ICD DAs based on a call that we had, so as part of that he is going to address this gap

**Comment by ocofaigh** [comment]
PR merged - closing
